SELECT
    BOOK.AUTHOR_ID,
    AUTHOR.AUTHOR_NAME,
    BOOK.CATEGORY,
    SUM(SALES.CNT * BOOK.PRICE) AS TOTAL_SALES
FROM 
    BOOK
RIGHT JOIN (
    SELECT 
        BOOK_ID,
        SUM(SALES) AS CNT
    FROM
        BOOK_SALES
    WHERE
        EXTRACT(YEAR_MONTH FROM SALES_DATE) = "202201"
    GROUP BY
        BOOK_ID
    ) AS SALES
ON 
    SALES.BOOK_ID = BOOK.BOOK_ID
JOIN 
    AUTHOR
ON
    AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
GROUP BY
    BOOK.AUTHOR_ID,
    AUTHOR.AUTHOR_NAME,
    BOOK.CATEGORY
ORDER BY
    BOOK.AUTHOR_ID ASC,
    BOOK.CATEGORY DESC