
SELECT
    RI.FOOD_TYPE,
    RI.REST_ID,
    RI.REST_NAME,
    RI.FAVORITES
FROM
    REST_INFO RI
JOIN (
    SELECT
        MAX(FAVORITES) AS FAVORITES,
        FOOD_TYPE
    FROM
        REST_INFO 
    GROUP BY
        FOOD_TYPE
) AS MF
ON 
    MF.FAVORITES = RI.FAVORITES AND
    MF.FOOD_TYPE = RI.FOOD_TYPE
ORDER BY
    RI.FOOD_TYPE DESC;