-- 코드를 입력하세요
SELECT ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES, ri.ADDRESS, ROUND(AVG(rr.REVIEW_SCORE), 2) as SCORE
FROM REST_INFO as ri
JOIN REST_REVIEW as rr
USING (REST_ID)
WHERE ri.ADDRESS LIKE '서울%'
GROUP BY ri.REST_ID
ORDER BY ROUND(AVG(rr.REVIEW_SCORE), 2) DESC, ri.FAVORITES DESC;