-- 코드를 입력하세요
WITH UIOS AS (
    SELECT
        OS.SALES_DATE,
        UI.GENDER,
        UI.USER_ID
    FROM
        ONLINE_SALE OS
    JOIN (
        SELECT
            USER_ID,
            GENDER
        FROM
            USER_INFO
        WHERE
            GENDER IS NOT NULL) AS UI
    ON
        UI.USER_ID = OS.USER_ID
)


SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT USER_ID) AS USERS
FROM 
    UIOS
GROUP BY
    YEAR(SALES_DATE),
    MONTH(SALES_DATE),
    GENDER
ORDER BY
    YEAR(SALES_DATE) ASC,
    MONTH(SALES_DATE) ASC,
    GENDER ASC;   