SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO I ON I.ITEM_ID = T.ITEM_ID
JOIN ITEM_INFO PARENT ON T.PARENT_ITEM_ID = PARENT.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY T.ITEM_ID DESC;