SELECT 
    YM.YEAR AS YEAR,
    YM.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA E
INNER JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM 
        ECOLI_DATA 
    GROUP BY
       YEAR
) AS YM
ON YM.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY 1 ASC, 2 ASC;